[NEW BONUS GUIDE] Wireguard VPN
twofaktor/minibolt pull request #30
Opened 2023-01-21 19:02 UTC by twofaktor

#### What

This PR proposes a new bonus guide to securely and privately remote access your MiniBolt node through the Wireguard server installed on MiniBolt and Wireguard client on your clients.

#### Why

We seek to connect to our own server without exposing our real IP to the rest of the network for security and privacy reasons, and at the same time to avoid using Tor for latency reasons

#### How

A complete guide explaining step by step how to build it

#### Scope

- [ ] significant change to core configuration
- [X] independent bonus guide
- [ ] simple bug fix

2023-01-28 10:50 UTC, 1ma commented
@twofaktor completed & ready to review.

2023-01-28 10:57 UTC, 1ma commented
> Why
>
> We seek to connect to our own server without exposing our real IP to the rest of the network for security and privacy
> reasons, and at the same time to avoid using Tor for latency reasons

WireGuard doesn't do anything to try to hide your IP, like Tor. But it makes it possible to access your MiniBolt services from outside your home network without having to open their ports to the internet.

WireGuard's traffic itself is encrypted, but it can be seen going to and from your real IP address.

2023-02-17 18:33 UTC, 1ma requested changes

2023-02-17 18:33 UTC, 1ma commented on guide/bonus/system/wireguard-VPN.md
> +Write the following contain and replace only `"<Your_Server_Private_Key>"` with the last obtained output:
contain -> content

2023-02-17 18:33 UTC, 1ma commented on guide/bonus/system/wireguard-VPN.md
> +For the purposes of this demo I've type a random subdomain `"yoursubdomain"`, but ***you can use anything memorable*** to you as long as no one has already taken that name.
type -> typed

2023-02-20 10:47 UTC, twofaktor commented
I merged this PR with changes of other topics wrongly, migrated to #38

2023-02-20 10:47 UTC, closed without merging